# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

def fibo_even_sum(number)
	sum = 0
	previous_digit = 1
	fibo_digit = 0;

	while fibo_digit < number
		temp = fibo_digit
		fibo_digit += previous_digit
		previous_digit = temp
		
		sum += fibo_digit if fibo_digit % 2 == 0
	end 
	sum
end

puts fibo_even_sum(4000000)
