using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExercisesProject.ExercisesB
{
    class _002_SumEvenFibonacciNumbers
    {
        /*
         Problem #2

         Each new term in the Fibonacci sequence is generated by adding the 
         previous two terms. 
         By starting with 1 and 2, the first 10 terms will be: 
         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         By considering the terms in the Fibonacci sequence whose values do 
         not exceed four million, find the sum of the even-valued terms.
         */
        public static void Run()
        {
            int result = 0;

            int fn_1 = 1;
            int fn_2 = 1;

            while ( fn_1 <= 4000000 )
            {
                if (fn_1 % 2 == 0)
                    result += fn_1;

                int fn_2Aux = fn_1;
                fn_1 = fn_2 + fn_1;
                fn_2 = fn_2Aux;
            }

            Console.WriteLine(
                "Sum of even fibonacci numbers below 4 million is: " + result);

            Console.ReadKey();
        }
    }
}
