/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 **/

class Solution {
    static int MAX_NUMBER = 4000000;

    public static long fiboEvenSum() {
        int b = 1;
        int c = 2, d;
        long sum = 0;

        //calculate the sum of even-valued in Fibonacci sequence not exceed 4,000,000
        while (c < MAX_NUMBER) {
            sum += c;
            d = b + (c << 0x01);
            c = d + b + c;
            b = d;
        }
        return sum;
    }

    public static void main(String[] args) {
        long sum = fiboEvenSum();
        System.out.println(sum);
    }
}
